# Generated by Django 2.1.2 on 2018-11-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField()),
                ('league_id', models.IntegerField()),
                ('league_name', models.CharField(max_length=100)),
                ('season_id', models.IntegerField()),
                ('season', models.CharField(max_length=100)),
                ('game_id', models.IntegerField()),
                ('gamedate', models.DateTimeField(blank=True, null=True)),
                ('teamname', models.CharField(max_length=100)),
                ('goals', models.IntegerField()),
                ('penalty', models.CharField(max_length=100)),
                ('result', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('player_id', models.IntegerField(unique=True)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('birthdate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
